name: key-value
services:
  db:
    image: mongodb/mongodb-community-server:7.0.18-ubuntu2204
    ports:
      - 27017:27017
    env_file:
      - .env.database
      - .env.dev
    volumes:
      - type: bind 
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: mongodb-data 
        target: /data/db 
    networks:
      -  key-value-net
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev 
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db 
    networks:
      - key-value-net
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
volumes:
  mongodb-data:
networks:
  key-value-net: