name: notes-backend
services:
  notes:
    build:
      context: . 
      dockerfile: Dockerfile
      target: development
    ports:
      - 9000:9000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    env_file:
      - .env
    networks:
      - notes-net
    depends_on:
      - notes-db
  notes-db:
    image: mongodb/mongodb-community-server:7.0.18-ubuntu2204
    volumes:
      - type: volume 
        source: notes-data
        target: /data/db
      - type: bind 
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    env_file:
      - .env
    networks:
      - notes-net 
volumes:
  notes-data:
networks:
  notes-net: